// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class EditProfiloSeleniumTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tC81() {
    driver.get("http://localhost:8080/VeicHomeIS/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.id("prova")).click();
    driver.findElement(By.id("text")).click();
    driver.findElement(By.id("text")).sendKeys("giuseppe70");
    driver.findElement(By.id("pass")).click();
    driver.findElement(By.id("pass")).sendKeys("qwerty1");
    driver.findElement(By.cssSelector("button:nth-child(3)")).click();
    driver.findElement(By.linkText("Mio Profilo")).click();
    driver.findElement(By.linkText("MODIFICA PROFILO")).click();
    driver.findElement(By.cssSelector("button:nth-child(7)")).click();
    assertThat(driver.switchTo().alert().getText(), is("Inserire dati mancanti"));
  }
  @Test
  public void tC83() {
    driver.get("http://localhost:8080/VeicHomeIS/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.linkText("Mio Profilo")).click();
    driver.findElement(By.linkText("MODIFICA PROFILO")).click();
    driver.findElement(By.name("id")).click();
    driver.findElement(By.name("id")).sendKeys("landolfo93");
    driver.findElement(By.cssSelector("button:nth-child(7)")).click();
    driver.findElement(By.id("ok")).click();
  }
  @Test
  public void tC84() {
    driver.get("http://localhost:8080/VeicHomeIS/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.id("prova")).click();
    driver.findElement(By.id("text")).click();
    driver.findElement(By.id("text")).sendKeys("giuseppe70");
    driver.findElement(By.id("pass")).click();
    driver.findElement(By.id("pass")).sendKeys("QWERTY1");
    driver.findElement(By.cssSelector("button:nth-child(3)")).click();
    driver.findElement(By.linkText("Mio Profilo")).click();
    driver.findElement(By.cssSelector("h2:nth-child(5)")).click();
    driver.findElement(By.linkText("MODIFICA PROFILO")).click();
    driver.findElement(By.name("indirizzo")).click();
    driver.findElement(By.name("indirizzo")).sendKeys("Via piave 21");
    driver.findElement(By.cssSelector("button:nth-child(7)")).click();
    driver.findElement(By.id("ok")).click();
  }
  @Test
  public void tC85() {
    driver.get("http://localhost:8080/VeicHomeIS/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.id("prova")).click();
    driver.findElement(By.id("text")).click();
    driver.findElement(By.id("text")).sendKeys("giuseppe70");
    driver.findElement(By.id("pass")).sendKeys("qwerty1");
    driver.findElement(By.id("pass")).sendKeys(Keys.ENTER);
    driver.findElement(By.linkText("Mio Profilo")).click();
    driver.findElement(By.linkText("MODIFICA PROFILO")).click();
    driver.findElement(By.name("id")).click();
    driver.findElement(By.name("id")).sendKeys("landolfo93");
    driver.findElement(By.name("indirizzo")).click();
    driver.findElement(By.name("indirizzo")).sendKeys("Via roma 5");
    driver.findElement(By.cssSelector("button:nth-child(7)")).click();
    driver.findElement(By.id("ok")).click();
  }
  @Test
  public void tC86() {
    driver.get("http://localhost:8080/VeicHomeIS/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.id("prova")).click();
    driver.findElement(By.id("text")).click();
    driver.findElement(By.id("text")).sendKeys("giuseppe70");
    driver.findElement(By.id("pass")).click();
    driver.findElement(By.id("pass")).sendKeys("qwerty1");
    driver.findElement(By.cssSelector("button:nth-child(3)")).click();
    driver.findElement(By.linkText("Mio Profilo")).click();
    driver.findElement(By.linkText("MODIFICA PROFILO")).click();
    driver.findElement(By.name("id")).click();
    driver.findElement(By.name("id")).sendKeys("landolfo93");
    driver.findElement(By.name("indirizzo")).click();
    driver.findElement(By.name("indirizzo")).sendKeys("Via -? roma 5");
    driver.findElement(By.cssSelector("button:nth-child(7)")).click();
    assertThat(driver.switchTo().alert().getText(), is("Hai inserito dei caratteri non validi."));
  }
  @Test
  public void tC87() {
    driver.get("http://localhost:8080/VeicHomeIS/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.id("prova")).click();
    driver.findElement(By.id("text")).click();
    driver.findElement(By.id("text")).sendKeys("giuseppe70");
    driver.findElement(By.id("pass")).click();
    driver.findElement(By.id("pass")).sendKeys("qwerty1");
    driver.findElement(By.cssSelector("button:nth-child(3)")).click();
    driver.findElement(By.linkText("Mio Profilo")).click();
    driver.findElement(By.linkText("MODIFICA PROFILO")).click();
    driver.findElement(By.name("numero_di_carta")).click();
    driver.findElement(By.name("numero_di_carta")).sendKeys("4485136236688436");
    driver.findElement(By.cssSelector("button:nth-child(7)")).click();
    assertThat(driver.switchTo().alert().getText(), is("Inserire carta,cvv e scadenza"));
  }
  @Test
  public void tC88() {
    driver.get("http://localhost:8080/VeicHomeIS/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.id("prova")).click();
    driver.findElement(By.id("text")).click();
    driver.findElement(By.id("text")).sendKeys("giuseppe70");
    driver.findElement(By.id("pass")).click();
    driver.findElement(By.id("pass")).sendKeys("qwerty1");
    driver.findElement(By.id("pass")).sendKeys(Keys.ENTER);
    driver.findElement(By.linkText("Mio Profilo")).click();
    driver.findElement(By.linkText("MODIFICA PROFILO")).click();
    driver.findElement(By.name("numero_di_carta")).click();
    driver.findElement(By.name("numero_di_carta")).sendKeys("4485136236688436");
    driver.findElement(By.name("cvv")).sendKeys("589");
    driver.findElement(By.cssSelector("button:nth-child(7)")).click();
    driver.findElement(By.id("ok")).click();
  }
  @Test
  public void tC89() {
    driver.get("http://localhost:8080/VeicHomeIS/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.id("prova")).click();
    driver.findElement(By.id("text")).click();
    driver.findElement(By.id("text")).sendKeys("giuseppe70");
    driver.findElement(By.id("pass")).click();
    driver.findElement(By.id("pass")).sendKeys("qwerty1");
    driver.findElement(By.cssSelector("button:nth-child(3)")).click();
    driver.findElement(By.linkText("Mio Profilo")).click();
    driver.findElement(By.linkText("MODIFICA PROFILO")).click();
    driver.findElement(By.name("numero_di_carta")).click();
    driver.findElement(By.name("numero_di_carta")).sendKeys("4485136236688436");
    driver.findElement(By.name("cvv")).sendKeys("589");
    driver.findElement(By.cssSelector("button:nth-child(7)")).click();
    driver.findElement(By.cssSelector("button")).click();
  }
  @Test
  public void tC810() {
    driver.get("http://localhost:8080/VeicHomeIS/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.id("prova")).click();
    driver.findElement(By.id("text")).click();
    driver.findElement(By.id("text")).sendKeys("giuseppe70");
    driver.findElement(By.id("pass")).click();
    driver.findElement(By.id("pass")).sendKeys("qwerty1");
    driver.findElement(By.cssSelector("button:nth-child(3)")).click();
    driver.findElement(By.linkText("Mio Profilo")).click();
    driver.findElement(By.cssSelector("h2:nth-child(5)")).click();
    driver.findElement(By.linkText("MODIFICA PROFILO")).click();
    driver.findElement(By.name("numero_di_carta")).click();
    driver.findElement(By.name("numero_di_carta")).sendKeys("44851988-*-18902");
    driver.findElement(By.name("cvv")).sendKeys("587");
    driver.findElement(By.cssSelector("button:nth-child(7)")).click();
    assertThat(driver.switchTo().alert().getText(), is("Dati errati"));
  }
  @Test
  public void tC811() {
    driver.get("http://localhost:8080/VeicHomeIS/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.id("prova")).click();
    driver.findElement(By.id("text")).click();
    driver.findElement(By.id("text")).sendKeys("giuseppe70");
    driver.findElement(By.id("pass")).click();
    driver.findElement(By.id("pass")).sendKeys("qwerty1");
    driver.findElement(By.cssSelector("button:nth-child(3)")).click();
    driver.findElement(By.linkText("Mio Profilo")).click();
    driver.findElement(By.linkText("MODIFICA PROFILO")).click();
    driver.findElement(By.name("numero_di_carta")).click();
    driver.findElement(By.name("numero_di_carta")).sendKeys("4485198854654456418902");
    driver.findElement(By.name("cvv")).click();
    driver.findElement(By.name("cvv")).sendKeys("789");
    driver.findElement(By.cssSelector("button:nth-child(7)")).click();
    assertThat(driver.switchTo().alert().getText(), is("Dati errati"));
  }
  @Test
  public void tC812() {
    driver.get("http://localhost:8080/VeicHomeIS/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.id("prova")).click();
    driver.findElement(By.id("text")).click();
    driver.findElement(By.id("text")).sendKeys("giuseppe70");
    driver.findElement(By.id("pass")).click();
    driver.findElement(By.id("pass")).sendKeys("qwerty1");
    driver.findElement(By.cssSelector("button:nth-child(3)")).click();
    driver.findElement(By.linkText("Mio Profilo")).click();
    driver.findElement(By.linkText("MODIFICA PROFILO")).click();
    driver.findElement(By.name("numero_di_carta")).click();
    driver.findElement(By.name("numero_di_carta")).sendKeys("4485198853818902");
    driver.findElement(By.name("cvv")).sendKeys("5/-");
    driver.findElement(By.cssSelector("button:nth-child(7)")).click();
    assertThat(driver.switchTo().alert().getText(), is("Dati errati"));
  }
  @Test
  public void tC813() {
    driver.get("http://localhost:8080/VeicHomeIS/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.id("prova")).click();
    driver.findElement(By.id("text")).click();
    driver.findElement(By.id("text")).sendKeys("giuseppe70");
    driver.findElement(By.id("pass")).sendKeys("qwerty1");
    driver.findElement(By.cssSelector("button:nth-child(3)")).click();
    driver.findElement(By.linkText("Mio Profilo")).click();
    driver.findElement(By.linkText("MODIFICA PROFILO")).click();
    driver.findElement(By.name("id")).click();
    driver.findElement(By.name("id")).sendKeys("landolfo92");
    driver.findElement(By.cssSelector("button:nth-child(7)")).click();
    driver.findElement(By.cssSelector("button")).click();
  }
}
