// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class InserimentoAutoSeleniumTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tC31() {
    driver.get("http://localhost:8080/VeicHomeIS/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.id("prova")).click();
    driver.findElement(By.id("text")).click();
    driver.findElement(By.id("text")).sendKeys("Tullio");
    driver.findElement(By.id("pass")).sendKeys("admin");
    driver.findElement(By.cssSelector("button:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".fa-car")).click();
    driver.findElement(By.id("ok")).click();
  }
  @Test
  public void tC32() {
    driver.get("http://localhost:8080/VeicHomeIS/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.id("prova")).click();
    driver.findElement(By.id("text")).click();
    driver.findElement(By.id("text")).sendKeys("Tullio");
    driver.findElement(By.id("pass")).click();
    driver.findElement(By.id("pass")).sendKeys("admin");
    driver.findElement(By.id("pass")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".fa-car")).click();
    driver.findElement(By.name("codice_telaio")).click();
    driver.findElement(By.name("codice_telaio")).sendKeys("vBKBNwaaj3r2s2886");
    driver.findElement(By.cssSelector("fieldset > #ok")).click();
    assertThat(driver.switchTo().alert().getText(), is("Inserisci dati mancanti"));
    driver.findElement(By.id("ok")).click();
  }
  @Test
  public void tC33() {
    driver.get("http://localhost:8080/VeicHomeIS/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.id("prova")).click();
    driver.findElement(By.id("text")).click();
    driver.findElement(By.id("text")).sendKeys("Tullio");
    driver.findElement(By.id("pass")).click();
    driver.findElement(By.id("pass")).sendKeys("ADMIN");
    driver.findElement(By.id("pass")).sendKeys(Keys.ENTER);
    driver.findElement(By.linkText("Inserisci Auto")).click();
    driver.findElement(By.name("codice_telaio")).click();
    driver.findElement(By.name("codice_telaio")).sendKeys("vBKBNwaaj3r2s2886");
    driver.findElement(By.name("targa")).click();
    driver.findElement(By.name("targa")).sendKeys("hg4587hg");
    driver.findElement(By.cssSelector("fieldset > #ok")).click();
    assertThat(driver.switchTo().alert().getText(), is("Inserisci dati mancanti"));
    driver.findElement(By.id("ok")).click();
  }
  @Test
  public void tC34() {
    driver.get("http://localhost:8080/VeicHomeIS/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.id("prova")).click();
    driver.findElement(By.cssSelector(".form-item:nth-child(1)")).click();
    driver.findElement(By.id("text")).click();
    driver.findElement(By.id("text")).sendKeys("Tullio");
    driver.findElement(By.id("pass")).sendKeys("ADMIN");
    driver.findElement(By.cssSelector("button:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".fa-car")).click();
    driver.findElement(By.cssSelector("fieldset")).click();
    driver.findElement(By.name("codice_telaio")).click();
    driver.findElement(By.name("codice_telaio")).sendKeys("vBKBNwaaj3r2s2886");
    driver.findElement(By.name("targa")).click();
    driver.findElement(By.name("targa")).sendKeys("hg4587hg");
    driver.findElement(By.name("colore")).click();
    driver.findElement(By.name("colore")).sendKeys("Blu");
    driver.findElement(By.cssSelector("fieldset > #ok")).click();
    assertThat(driver.switchTo().alert().getText(), is("Inserisci dati mancanti"));
    driver.findElement(By.id("ok")).click();
  }
  @Test
  public void tC35() {
    driver.get("http://localhost:8080/VeicHomeIS/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.id("prova")).click();
    driver.findElement(By.id("text")).click();
    driver.findElement(By.id("text")).sendKeys("Tullio");
    driver.findElement(By.id("pass")).click();
    driver.findElement(By.id("pass")).sendKeys("admin");
    driver.findElement(By.id("pass")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".fa-car")).click();
    driver.findElement(By.name("codice_telaio")).click();
    driver.findElement(By.name("codice_telaio")).sendKeys("vBKBNwaaj3r2s2886");
    driver.findElement(By.name("targa")).click();
    driver.findElement(By.name("targa")).sendKeys("hg4587hg");
    driver.findElement(By.name("colore")).click();
    driver.findElement(By.name("colore")).sendKeys("Blu");
    driver.findElement(By.name("marchio")).click();
    driver.findElement(By.name("marchio")).sendKeys("Alfa romeo");
    driver.findElement(By.cssSelector("fieldset > #ok")).click();
    assertThat(driver.switchTo().alert().getText(), is("Inserisci dati mancanti"));
    driver.findElement(By.id("ok")).click();
  }
  @Test
  public void tC36() {
    driver.get("http://localhost:8080/VeicHomeIS/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.id("prova")).click();
    driver.findElement(By.id("text")).click();
    driver.findElement(By.id("text")).sendKeys("Tullio");
    driver.findElement(By.id("pass")).click();
    driver.findElement(By.id("pass")).sendKeys("admin");
    driver.findElement(By.id("pass")).sendKeys(Keys.ENTER);
    driver.findElement(By.linkText("Inserisci Auto")).click();
    driver.findElement(By.name("codice_telaio")).click();
    driver.findElement(By.name("codice_telaio")).sendKeys("vBKBNwaaj3r2s2886");
    driver.findElement(By.name("targa")).click();
    driver.findElement(By.name("targa")).sendKeys("hg4587hg");
    driver.findElement(By.name("colore")).click();
    driver.findElement(By.name("colore")).sendKeys("Blu");
    driver.findElement(By.name("marchio")).click();
    driver.findElement(By.name("marchio")).sendKeys("Alfa romeo");
    driver.findElement(By.name("modello")).click();
    driver.findElement(By.name("modello")).sendKeys("Giulia");
    driver.findElement(By.cssSelector("fieldset > #ok")).click();
    assertThat(driver.switchTo().alert().getText(), is("Inserisci dati mancanti"));
    driver.findElement(By.id("ok")).click();
  }
  @Test
  public void tC37() {
    driver.get("http://localhost:8080/VeicHomeIS/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.id("prova")).click();
    driver.findElement(By.id("text")).click();
    driver.findElement(By.id("text")).sendKeys("Tullio");
    driver.findElement(By.id("pass")).sendKeys("admin");
    driver.findElement(By.cssSelector("button:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".fa-car")).click();
    driver.findElement(By.name("codice_telaio")).click();
    driver.findElement(By.name("codice_telaio")).sendKeys("vBKBNwaaj3r2s2886");
    driver.findElement(By.name("targa")).click();
    driver.findElement(By.name("targa")).sendKeys("hg4587hg");
    driver.findElement(By.name("colore")).click();
    driver.findElement(By.name("colore")).sendKeys("Blu");
    driver.findElement(By.name("marchio")).click();
    driver.findElement(By.name("marchio")).sendKeys("Alfa romeo");
    driver.findElement(By.name("modello")).click();
    driver.findElement(By.name("modello")).sendKeys("Giulia");
    driver.findElement(By.name("kw")).click();
    driver.findElement(By.name("kw")).sendKeys("110");
    driver.findElement(By.cssSelector("fieldset > #ok")).click();
    assertThat(driver.switchTo().alert().getText(), is("Inserisci dati mancanti"));
    driver.findElement(By.id("ok")).click();
  }
  @Test
  public void tC38() {
    driver.get("http://localhost:8080/VeicHomeIS/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.id("prova")).click();
    driver.findElement(By.id("text")).click();
    driver.findElement(By.id("text")).sendKeys("Tullio");
    driver.findElement(By.id("pass")).click();
    driver.findElement(By.id("pass")).sendKeys("admin");
    driver.findElement(By.cssSelector("button:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".fa-car")).click();
    driver.findElement(By.name("codice_telaio")).click();
    driver.findElement(By.name("codice_telaio")).sendKeys("vBKBNwaaj3r2s2886");
    driver.findElement(By.name("targa")).click();
    driver.findElement(By.name("targa")).sendKeys("hg4587hg");
    driver.findElement(By.name("colore")).click();
    driver.findElement(By.name("colore")).sendKeys("Blu");
    driver.findElement(By.name("marchio")).click();
    driver.findElement(By.name("marchio")).sendKeys("Alfa romeo");
    driver.findElement(By.name("modello")).click();
    driver.findElement(By.name("modello")).sendKeys("Giulia");
    driver.findElement(By.name("kw")).click();
    driver.findElement(By.name("kw")).sendKeys("110");
    driver.findElement(By.name("prezzo")).click();
    driver.findElement(By.name("prezzo")).sendKeys("47000");
    driver.findElement(By.cssSelector("fieldset > #ok")).click();
    assertThat(driver.switchTo().alert().getText(), is("Inserisci dati mancanti"));
    driver.findElement(By.id("ok")).click();
  }
  @Test
  public void tC39() {
    driver.get("http://localhost:8080/VeicHomeIS/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.id("prova")).click();
    driver.findElement(By.id("text")).click();
    driver.findElement(By.id("text")).sendKeys("Tullio");
    driver.findElement(By.id("pass")).click();
    driver.findElement(By.id("pass")).sendKeys("admin");
    driver.findElement(By.id("pass")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".fa-car")).click();
    driver.findElement(By.name("codice_telaio")).click();
    driver.findElement(By.name("codice_telaio")).sendKeys("vBKBNwaaj3r2s2886");
    driver.findElement(By.name("targa")).click();
    driver.findElement(By.name("targa")).sendKeys("hg4587hg");
    driver.findElement(By.name("colore")).click();
    driver.findElement(By.name("colore")).sendKeys("Blu");
    driver.findElement(By.name("marchio")).click();
    driver.findElement(By.name("marchio")).sendKeys("Alfa romeo");
    driver.findElement(By.name("modello")).click();
    driver.findElement(By.name("modello")).sendKeys("Giulia");
    driver.findElement(By.name("kw")).click();
    driver.findElement(By.name("kw")).sendKeys("110");
    driver.findElement(By.name("prezzo")).click();
    driver.findElement(By.name("prezzo")).sendKeys("47000");
    driver.findElement(By.name("photo")).click();
    driver.findElement(By.name("photo")).sendKeys("D:\\Desktop\\giulia.png");
    driver.findElement(By.cssSelector("fieldset > #ok")).click();
    assertThat(driver.switchTo().alert().getText(), is("Inserisci dati mancanti"));
    driver.findElement(By.id("ok")).click();
  }
  @Test
  public void tC310() {
    driver.get("http://localhost:8080/VeicHomeIS/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.id("prova")).click();
    driver.findElement(By.id("text")).click();
    driver.findElement(By.id("text")).sendKeys("Tullio");
    driver.findElement(By.id("pass")).sendKeys("admin");
    driver.findElement(By.cssSelector("button:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".fa-car")).click();
    driver.findElement(By.name("codice_telaio")).click();
    driver.findElement(By.name("codice_telaio")).sendKeys("vBKBNwaaj3r2s2886");
    driver.findElement(By.name("targa")).click();
    driver.findElement(By.name("targa")).sendKeys("hg4587hg");
    driver.findElement(By.name("colore")).click();
    driver.findElement(By.name("colore")).sendKeys("Blu");
    driver.findElement(By.name("marchio")).click();
    driver.findElement(By.name("marchio")).sendKeys("Alfa romeo");
    driver.findElement(By.name("modello")).click();
    driver.findElement(By.name("modello")).sendKeys("Giulia");
    driver.findElement(By.name("kw")).click();
    driver.findElement(By.name("kw")).sendKeys("110");
    driver.findElement(By.name("prezzo")).click();
    driver.findElement(By.name("prezzo")).sendKeys("47000");
    driver.findElement(By.name("sconto")).click();
    driver.findElement(By.name("sconto")).sendKeys("2%");
    driver.findElement(By.name("photo")).click();
    driver.findElement(By.name("photo")).sendKeys("D:\\Desktop\\giulia.png");
    driver.findElement(By.cssSelector("fieldset > #ok")).click();
    assertThat(driver.switchTo().alert().getText(), is("Inserisci dati mancanti"));
    driver.findElement(By.id("ok")).click();
  }
  @Test
  public void tC311() {
    driver.get("http://localhost:8080/VeicHomeIS/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.id("prova")).click();
    driver.findElement(By.id("text")).click();
    driver.findElement(By.id("text")).sendKeys("Tullio");
    driver.findElement(By.id("pass")).sendKeys("admin");
    driver.findElement(By.id("pass")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".fa-car")).click();
    driver.findElement(By.name("codice_telaio")).click();
    driver.findElement(By.name("codice_telaio")).sendKeys("vBKBNwaaj3r2s2886");
    driver.findElement(By.name("targa")).click();
    driver.findElement(By.name("targa")).sendKeys("hg4587hg");
    driver.findElement(By.name("colore")).click();
    driver.findElement(By.name("colore")).sendKeys("Blu");
    driver.findElement(By.name("marchio")).click();
    driver.findElement(By.name("marchio")).sendKeys("Alfa romeo");
    driver.findElement(By.name("modello")).click();
    driver.findElement(By.name("modello")).sendKeys("Giulia");
    driver.findElement(By.name("kw")).click();
    driver.findElement(By.name("kw")).sendKeys("110");
    driver.findElement(By.name("prezzo")).click();
    driver.findElement(By.name("prezzo")).sendKeys("47000");
    driver.findElement(By.name("sconto")).click();
    driver.findElement(By.name("sconto")).sendKeys("2%");
    driver.findElement(By.name("numero_di_passegeri")).click();
    driver.findElement(By.name("numero_di_passegeri")).sendKeys("5");
    driver.findElement(By.name("photo")).click();
    driver.findElement(By.name("photo")).sendKeys("D:\\Desktop\\giulia.png");
    driver.findElement(By.cssSelector("fieldset > #ok")).click();
    driver.findElement(By.id("ok")).click();
  }
  @Test
  public void tC312() {
    driver.get("http://localhost:8080/VeicHomeIS/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.id("prova")).click();
    driver.findElement(By.id("text")).click();
    driver.findElement(By.id("text")).sendKeys("Tullio");
    driver.findElement(By.id("pass")).sendKeys("admin");
    driver.findElement(By.id("pass")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".fa-car")).click();
    driver.findElement(By.name("codice_telaio")).click();
    driver.findElement(By.name("codice_telaio")).sendKeys("vBKBNwaaj3r2s2886");
    driver.findElement(By.name("targa")).click();
    driver.findElement(By.name("targa")).sendKeys("hg4587hg");
    driver.findElement(By.name("colore")).click();
    driver.findElement(By.name("colore")).sendKeys("Blu");
    driver.findElement(By.name("marchio")).click();
    driver.findElement(By.name("marchio")).sendKeys("Alfa romeo");
    driver.findElement(By.name("modello")).click();
    driver.findElement(By.name("modello")).sendKeys("Giulia");
    driver.findElement(By.name("kw")).click();
    driver.findElement(By.name("kw")).sendKeys("110");
    driver.findElement(By.name("prezzo")).click();
    driver.findElement(By.name("prezzo")).sendKeys("47000");
    driver.findElement(By.name("sconto")).click();
    driver.findElement(By.name("sconto")).sendKeys("2%");
    driver.findElement(By.name("numero_di_passegeri")).click();
    driver.findElement(By.name("numero_di_passegeri")).sendKeys("5");
    driver.findElement(By.name("photo")).click();
    driver.findElement(By.name("photo")).sendKeys("D:\\Desktop\\giulia.png");
    driver.findElement(By.cssSelector("fieldset > #ok")).click();
    driver.findElement(By.id("ok")).click();
  }
}
