// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class InserimentoMotoSeleniumTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tC41() {
    driver.get("http://localhost:8080/VeicHomeIS/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.id("prova")).click();
    driver.findElement(By.id("text")).click();
    driver.findElement(By.id("text")).sendKeys("Tullio");
    driver.findElement(By.id("pass")).sendKeys("admin");
    driver.findElement(By.cssSelector("button:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".fa-motorcycle")).click();
    driver.findElement(By.id("ok")).click();
  }
  @Test
  public void tC42() {
    driver.get("http://localhost:8080/VeicHomeIS/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.id("prova")).click();
    driver.findElement(By.id("text")).click();
    driver.findElement(By.id("text")).sendKeys("Tullio");
    driver.findElement(By.id("pass")).click();
    driver.findElement(By.id("pass")).sendKeys("admin");
    driver.findElement(By.id("pass")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".fa-motorcycle")).click();
    driver.findElement(By.name("codice_telaio")).click();
    driver.findElement(By.name("codice_telaio")).sendKeys("rom3x87rt6jhm5014");
    driver.findElement(By.cssSelector("fieldset > #ok")).click();
    assertThat(driver.switchTo().alert().getText(), is("Inserisci dati mancanti"));
    driver.findElement(By.id("ok")).click();
  }
  @Test
  public void tC43() {
    driver.get("http://localhost:8080/VeicHomeIS/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.id("prova")).click();
    driver.findElement(By.id("text")).click();
    driver.findElement(By.id("text")).sendKeys("Tullio");
    driver.findElement(By.id("pass")).click();
    driver.findElement(By.id("pass")).sendKeys("ADMIN");
    driver.findElement(By.id("pass")).sendKeys(Keys.ENTER);
    driver.findElement(By.linkText("Inserisci Moto")).click();
    driver.findElement(By.name("codice_telaio")).click();
    driver.findElement(By.name("codice_telaio")).sendKeys("rom3x87rt6jhm5014");
    driver.findElement(By.name("targa")).click();
    driver.findElement(By.name("targa")).sendKeys("fg380dh");
    driver.findElement(By.cssSelector("fieldset > #ok")).click();
    assertThat(driver.switchTo().alert().getText(), is("Inserisci dati mancanti"));
    driver.findElement(By.id("ok")).click();
  }
  @Test
  public void tC44() {
    driver.get("http://localhost:8080/VeicHomeIS/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.id("prova")).click();
    driver.findElement(By.cssSelector(".form-item:nth-child(1)")).click();
    driver.findElement(By.id("text")).click();
    driver.findElement(By.id("text")).sendKeys("Tullio");
    driver.findElement(By.id("pass")).sendKeys("ADMIN");
    driver.findElement(By.cssSelector("button:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".fa-motorcycle")).click();
    driver.findElement(By.cssSelector("fieldset")).click();
    driver.findElement(By.name("codice_telaio")).click();
    driver.findElement(By.name("codice_telaio")).sendKeys("rom3x87rt6jhm5014");
    driver.findElement(By.name("targa")).click();
    driver.findElement(By.name("targa")).sendKeys("fg380dh");
    driver.findElement(By.name("colore")).click();
    driver.findElement(By.name("colore")).sendKeys("Rosso");
    driver.findElement(By.cssSelector("fieldset > #ok")).click();
    assertThat(driver.switchTo().alert().getText(), is("Inserisci dati mancanti"));
    driver.findElement(By.id("ok")).click();
  }
  @Test
  public void tC45() {
    driver.get("http://localhost:8080/VeicHomeIS/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.id("prova")).click();
    driver.findElement(By.id("text")).click();
    driver.findElement(By.id("text")).sendKeys("Tullio");
    driver.findElement(By.id("pass")).click();
    driver.findElement(By.id("pass")).sendKeys("admin");
    driver.findElement(By.id("pass")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".fa-motorcycle")).click();
    driver.findElement(By.name("codice_telaio")).click();
    driver.findElement(By.name("codice_telaio")).sendKeys("rom3x87rt6jhm5014");
    driver.findElement(By.name("targa")).click();
    driver.findElement(By.name("targa")).sendKeys("fg380dh");
    driver.findElement(By.name("colore")).click();
    driver.findElement(By.name("colore")).sendKeys("Rosso");
    driver.findElement(By.name("marchio")).click();
    driver.findElement(By.name("marchio")).sendKeys("Ducati");
    driver.findElement(By.cssSelector("fieldset > #ok")).click();
    assertThat(driver.switchTo().alert().getText(), is("Inserisci dati mancanti"));
    driver.findElement(By.id("ok")).click();
  }
  @Test
  public void tC46() {
    driver.get("http://localhost:8080/VeicHomeIS/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.id("prova")).click();
    driver.findElement(By.id("text")).click();
    driver.findElement(By.id("text")).sendKeys("Tullio");
    driver.findElement(By.id("pass")).click();
    driver.findElement(By.id("pass")).sendKeys("admin");
    driver.findElement(By.id("pass")).sendKeys(Keys.ENTER);
    driver.findElement(By.linkText("Inserisci Moto")).click();
    driver.findElement(By.name("codice_telaio")).click();
    driver.findElement(By.name("codice_telaio")).sendKeys("rom3x87rt6jhm5014");
    driver.findElement(By.name("targa")).click();
    driver.findElement(By.name("targa")).sendKeys("fg380dh");
    driver.findElement(By.name("colore")).click();
    driver.findElement(By.name("colore")).sendKeys("Rosso");
    driver.findElement(By.name("marchio")).click();
    driver.findElement(By.name("marchio")).sendKeys("Ducati");
    driver.findElement(By.name("modello")).click();
    driver.findElement(By.name("modello")).sendKeys("Panigale-V4");
    driver.findElement(By.cssSelector("fieldset > #ok")).click();
    assertThat(driver.switchTo().alert().getText(), is("Inserisci dati mancanti"));
    driver.findElement(By.id("ok")).click();
  }
  @Test
  public void tC47() {
    driver.get("http://localhost:8080/VeicHomeIS/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.id("prova")).click();
    driver.findElement(By.id("text")).click();
    driver.findElement(By.id("text")).sendKeys("Tullio");
    driver.findElement(By.id("pass")).sendKeys("admin");
    driver.findElement(By.cssSelector("button:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".fa-motorcycle")).click();
    driver.findElement(By.name("codice_telaio")).click();
    driver.findElement(By.name("codice_telaio")).sendKeys("rom3x87rt6jhm5014");
    driver.findElement(By.name("targa")).click();
    driver.findElement(By.name("targa")).sendKeys("fg380dh");
    driver.findElement(By.name("colore")).click();
    driver.findElement(By.name("colore")).sendKeys("Rosso");
    driver.findElement(By.name("marchio")).click();
    driver.findElement(By.name("marchio")).sendKeys("Ducati");
    driver.findElement(By.name("modello")).click();
    driver.findElement(By.name("modello")).sendKeys("Panigale-V4");
    driver.findElement(By.name("kw")).click();
    driver.findElement(By.name("kw")).sendKeys("157");
    driver.findElement(By.cssSelector("fieldset > #ok")).click();
    assertThat(driver.switchTo().alert().getText(), is("Inserisci dati mancanti"));
    driver.findElement(By.id("ok")).click();
  }
  @Test
  public void tC48() {
    driver.get("http://localhost:8080/VeicHomeIS/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.id("prova")).click();
    driver.findElement(By.id("text")).click();
    driver.findElement(By.id("text")).sendKeys("Tullio");
    driver.findElement(By.id("pass")).click();
    driver.findElement(By.id("pass")).sendKeys("admin");
    driver.findElement(By.cssSelector("button:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".fa-motorcycle")).click();
    driver.findElement(By.name("codice_telaio")).click();
    driver.findElement(By.name("codice_telaio")).sendKeys("rom3x87rt6jhm5014");
    driver.findElement(By.name("targa")).click();
    driver.findElement(By.name("targa")).sendKeys("fg380dh");
    driver.findElement(By.name("colore")).click();
    driver.findElement(By.name("colore")).sendKeys("Rosso");
    driver.findElement(By.name("marchio")).click();
    driver.findElement(By.name("marchio")).sendKeys("Ducati");
    driver.findElement(By.name("modello")).click();
    driver.findElement(By.name("modello")).sendKeys("Panigale-V4");
    driver.findElement(By.name("kw")).click();
    driver.findElement(By.name("kw")).sendKeys("157");
    driver.findElement(By.name("prezzo")).click();
    driver.findElement(By.name("prezzo")).sendKeys("29990");
    driver.findElement(By.cssSelector("fieldset > #ok")).click();
    assertThat(driver.switchTo().alert().getText(), is("Inserisci dati mancanti"));
    driver.findElement(By.id("ok")).click();
  }
  @Test
  public void tC49() {
    driver.get("http://localhost:8080/VeicHomeIS/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.id("prova")).click();
    driver.findElement(By.id("text")).click();
    driver.findElement(By.id("text")).sendKeys("Tullio");
    driver.findElement(By.id("pass")).click();
    driver.findElement(By.id("pass")).sendKeys("admin");
    driver.findElement(By.id("pass")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".fa-motorcycle")).click();
    driver.findElement(By.name("codice_telaio")).click();
    driver.findElement(By.name("codice_telaio")).sendKeys("rom3x87rt6jhm5014");
    driver.findElement(By.name("targa")).click();
    driver.findElement(By.name("targa")).sendKeys("fg380dh");
    driver.findElement(By.name("colore")).click();
    driver.findElement(By.name("colore")).sendKeys("Rosso");
    driver.findElement(By.name("marchio")).click();
    driver.findElement(By.name("marchio")).sendKeys("Ducati");
    driver.findElement(By.name("modello")).click();
    driver.findElement(By.name("modello")).sendKeys("Panigale-V4");
    driver.findElement(By.name("kw")).click();
    driver.findElement(By.name("kw")).sendKeys("157");
    driver.findElement(By.name("prezzo")).click();
    driver.findElement(By.name("prezzo")).sendKeys("29990");
    driver.findElement(By.name("photo")).click();
    driver.findElement(By.name("photo")).sendKeys("D:\\Desktop\\ducati.png");
    driver.findElement(By.cssSelector("fieldset > #ok")).click();
    assertThat(driver.switchTo().alert().getText(), is("Inserisci dati mancanti"));
    driver.findElement(By.id("ok")).click();
  }
  @Test
  public void tC410() {
    driver.get("http://localhost:8080/VeicHomeIS/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.id("prova")).click();
    driver.findElement(By.id("text")).click();
    driver.findElement(By.id("text")).sendKeys("Tullio");
    driver.findElement(By.id("pass")).sendKeys("admin");
    driver.findElement(By.cssSelector("button:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".fa-motorcycle")).click();
    driver.findElement(By.name("codice_telaio")).click();
    driver.findElement(By.name("codice_telaio")).sendKeys("rom3x87rt6jhm5014");
    driver.findElement(By.name("targa")).click();
    driver.findElement(By.name("targa")).sendKeys("fg380dh");
    driver.findElement(By.name("colore")).click();
    driver.findElement(By.name("colore")).sendKeys("Rosso");
    driver.findElement(By.name("marchio")).click();
    driver.findElement(By.name("marchio")).sendKeys("Ducati");
    driver.findElement(By.name("modello")).click();
    driver.findElement(By.name("modello")).sendKeys("Panigale-V4");
    driver.findElement(By.name("kw")).click();
    driver.findElement(By.name("kw")).sendKeys("157");
    driver.findElement(By.name("prezzo")).click();
    driver.findElement(By.name("prezzo")).sendKeys("29990");
    driver.findElement(By.name("accessori")).click();
    driver.findElement(By.name("accessori")).sendKeys("Borsa da serbatoio");
    driver.findElement(By.name("photo")).click();
    driver.findElement(By.name("photo")).sendKeys("D:\\Desktop\\ducati.png");
    driver.findElement(By.cssSelector("fieldset > #ok")).click();
    assertThat(driver.switchTo().alert().getText(), is("Inserisci dati mancanti"));
    driver.findElement(By.id("ok")).click();
  }
  @Test
  public void tC411() {
    driver.get("http://localhost:8080/VeicHomeIS/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.id("prova")).click();
    driver.findElement(By.id("text")).click();
    driver.findElement(By.id("text")).sendKeys("Tullio");
    driver.findElement(By.id("pass")).sendKeys("admin");
    driver.findElement(By.id("pass")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".fa-motorcycle")).click();
    driver.findElement(By.name("codice_telaio")).click();
    driver.findElement(By.name("codice_telaio")).sendKeys("rom3x87rt6jhm5014");
    driver.findElement(By.name("targa")).click();
    driver.findElement(By.name("targa")).sendKeys("fg380dh");
    driver.findElement(By.name("colore")).click();
    driver.findElement(By.name("colore")).sendKeys("Rosso");
    driver.findElement(By.name("marchio")).click();
    driver.findElement(By.name("marchio")).sendKeys("Ducati");
    driver.findElement(By.name("modello")).click();
    driver.findElement(By.name("modello")).sendKeys("Panigale-V4");
    driver.findElement(By.name("kw")).click();
    driver.findElement(By.name("kw")).sendKeys("157");
    driver.findElement(By.name("prezzo")).click();
    driver.findElement(By.name("prezzo")).sendKeys("29990");
    driver.findElement(By.name("accessori")).click();
    driver.findElement(By.name("accessori")).sendKeys("Borsa da serbatoio");
    driver.findElement(By.name("custom")).click();
    driver.findElement(By.name("custom")).sendKeys("Si");
    driver.findElement(By.name("photo")).click();
    driver.findElement(By.name("photo")).sendKeys("D:\\Desktop\\ducati.png");
    driver.findElement(By.cssSelector("fieldset > #ok")).click();
    driver.findElement(By.id("ok")).click();
  }
}
